- menu_name: "Contact"
  
- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "Media"
  url: "/media/"
  title: "Media"

- name: "RSS News Feed"
  url: "/feed.xml"
  title: "Subscribe to ASC News via RSS"
  
- name: "Atom News Feed"
  url: "/atom.xml"
  title: "Subscribe to ASC News via Atom"

