- menu_name: "Contact"
  
- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "Media"
  url: "/media/"
  title: "Media"

- name: "RSS News Feed"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

